name: Select OpenCode model
description: Selects OpenRouter model based on keywords in input text
inputs:
  input-text:
    description: Text to inspect for model keywords (e.g. codex, glm, kimi)
    required: true
outputs:
  model:
    description: Selected OpenRouter model
    value: ${{ steps.select-model.outputs.model }}
  cleaned-text:
    description: Input text with model keywords and command prefixes removed
    value: ${{ steps.select-model.outputs.cleaned_text }}
runs:
  using: composite
  steps:
    - name: Determine model based on input text
      id: select-model
      shell: bash
      env:
        INPUT_TEXT: ${{ inputs.input-text }}
      run: |
        if [[ "$INPUT_TEXT" == *"codex"* ]]; then
          echo "model=openrouter/openai/gpt-5.3-codex" >> $GITHUB_OUTPUT
        elif [[ "$INPUT_TEXT" == *"glm"* ]]; then
          echo "model=openrouter/z-ai/glm-5" >> $GITHUB_OUTPUT
        elif [[ "$INPUT_TEXT" == *"kimi"* ]]; then
          echo "model=openrouter/moonshotai/kimi-k2.5" >> $GITHUB_OUTPUT
        else
          echo "model=zai-coding-plan/glm-5" >> $GITHUB_OUTPUT
        fi
        CLEANED="${INPUT_TEXT//\/oc/}"
        CLEANED="${CLEANED//\/opencode/}"
        CLEANED="${CLEANED//codex/}"
        CLEANED="${CLEANED//glm/}"
        CLEANED="${CLEANED//kimi/}"
        echo "cleaned_text=$CLEANED" >> $GITHUB_OUTPUT
